name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## What’s Changed

  $CHANGES
categories:
  - title: 'New Features'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Dependency Updates'
    label: 'dependencies'
